// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVCHostMvcApp.Areas.FeatureFolderArea.FeatureFoo
{
    public partial class FeatureFooController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FeatureFooController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FeatureFooController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Foobar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Foobar);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FeatureFooController Actions { get { return MVC.FeatureFolderArea.FeatureFoo; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "FeatureFolderArea";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "FeatureFoo";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "FeatureFoo";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Foobar = "Foobar";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Foobar = "Foobar";
        }


        static readonly ActionParamsClass_Foobar s_params_Foobar = new ActionParamsClass_Foobar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Foobar FoobarParams { get { return s_params_Foobar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Foobar
        {
            public readonly string param = "param";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Foobar = "Foobar";
                public readonly string Index = "Index";
            }
            public readonly string Foobar = "~/Areas/FeatureFolderArea/FeatureFoo/Foobar.txt";
            public readonly string Index = "~/Areas/FeatureFolderArea/FeatureFoo/Index.txt";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_FeatureFooController : T4MVCHostMvcApp.Areas.FeatureFolderArea.FeatureFoo.FeatureFooController
    {
        public T4MVC_FeatureFooController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FoobarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string param);

        [NonAction]
        public override System.Web.Mvc.ActionResult Foobar(string param)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Foobar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            FoobarOverride(callInfo, param);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
