// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AnotherPartial = "AnotherPartial";
                public readonly string DuplicateControl = "DuplicateControl";
                public readonly string DuplicateControl1 = "DuplicateControl1";
                public readonly string Error = "Error";
                public readonly string LogOnUserControl = "LogOnUserControl";
            }
            public readonly string AnotherPartial = "~/Views/Shared/AnotherPartial.ascx";
            public readonly string DuplicateControl = "~/Views/Shared/DuplicateControl.ascx";
            public readonly string DuplicateControl1 = "~/Views/Shared/DuplicateControl1.ascx";
            public readonly string Error = "~/Views/Shared/Error.aspx";
            public readonly string LogOnUserControl = "~/Views/Shared/LogOnUserControl.ascx";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
