// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly breakClass s_break = new breakClass();
    public static breakClass @break { get { return s_break; } }
    static readonly FeatureFolderAreaClass s_FeatureFolderArea = new FeatureFolderAreaClass();
    public static FeatureFolderAreaClass FeatureFolderArea { get { return s_FeatureFolderArea; } }
    static readonly HomeClass s_Home = new HomeClass();
    public static HomeClass HomeArea { get { return s_Home; } }
    public static T4MVCHostMvcApp.Controllers.DefaultController Default = new T4MVCHostMvcApp.Controllers.T4MVC_DefaultController();
    public static T4MVCHostMvcApp.Controllers.HomeController Home = new T4MVCHostMvcApp.Controllers.T4MVC_HomeController();
    public static T4MVCHostMvcApp.Controllers.Ctrl1Controller Ctrl1 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl1Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl2Controller Ctrl2 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl2Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl3Controller Ctrl3 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl3Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl4Controller Ctrl4 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl4Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl5Controller Ctrl5 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl5Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl6Controller Ctrl6 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl6Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl7Controller Ctrl7 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl7Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl8Controller Ctrl8 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl8Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl9Controller Ctrl9 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl9Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl10Controller Ctrl10 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl10Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl11Controller Ctrl11 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl11Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl12Controller Ctrl12 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl12Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl13Controller Ctrl13 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl13Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl14Controller Ctrl14 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl14Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl15Controller Ctrl15 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl15Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl16Controller Ctrl16 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl16Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl17Controller Ctrl17 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl17Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl18Controller Ctrl18 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl18Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl19Controller Ctrl19 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl19Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl20Controller Ctrl20 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl20Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl21Controller Ctrl21 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl21Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl22Controller Ctrl22 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl22Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl23Controller Ctrl23 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl23Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl24Controller Ctrl24 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl24Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl25Controller Ctrl25 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl25Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl26Controller Ctrl26 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl26Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl27Controller Ctrl27 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl27Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl28Controller Ctrl28 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl28Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl29Controller Ctrl29 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl29Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl30Controller Ctrl30 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl30Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl31Controller Ctrl31 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl31Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl32Controller Ctrl32 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl32Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl33Controller Ctrl33 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl33Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl34Controller Ctrl34 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl34Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl35Controller Ctrl35 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl35Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl36Controller Ctrl36 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl36Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl37Controller Ctrl37 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl37Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl38Controller Ctrl38 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl38Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl39Controller Ctrl39 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl39Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl40Controller Ctrl40 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl40Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl41Controller Ctrl41 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl41Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl42Controller Ctrl42 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl42Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl43Controller Ctrl43 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl43Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl44Controller Ctrl44 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl44Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl45Controller Ctrl45 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl45Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl46Controller Ctrl46 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl46Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl47Controller Ctrl47 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl47Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl48Controller Ctrl48 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl48Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl49Controller Ctrl49 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl49Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl50Controller Ctrl50 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl50Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl51Controller Ctrl51 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl51Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl52Controller Ctrl52 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl52Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl53Controller Ctrl53 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl53Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl54Controller Ctrl54 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl54Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl55Controller Ctrl55 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl55Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl56Controller Ctrl56 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl56Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl57Controller Ctrl57 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl57Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl58Controller Ctrl58 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl58Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl59Controller Ctrl59 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl59Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl60Controller Ctrl60 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl60Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl61Controller Ctrl61 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl61Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl62Controller Ctrl62 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl62Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl63Controller Ctrl63 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl63Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl64Controller Ctrl64 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl64Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl65Controller Ctrl65 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl65Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl66Controller Ctrl66 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl66Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl67Controller Ctrl67 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl67Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl68Controller Ctrl68 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl68Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl69Controller Ctrl69 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl69Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl70Controller Ctrl70 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl70Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl71Controller Ctrl71 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl71Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl72Controller Ctrl72 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl72Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl73Controller Ctrl73 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl73Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl74Controller Ctrl74 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl74Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl75Controller Ctrl75 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl75Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl76Controller Ctrl76 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl76Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl77Controller Ctrl77 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl77Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl78Controller Ctrl78 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl78Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl79Controller Ctrl79 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl79Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl80Controller Ctrl80 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl80Controller();
    public static T4MVCHostMvcApp.Controllers.Ctrl81Controller Ctrl81 = new T4MVCHostMvcApp.Controllers.T4MVC_Ctrl81Controller();
    public static T4MVCHostMvcApp.Controllers.ModelUnbinderController ModelUnbinder = new T4MVCHostMvcApp.Controllers.T4MVC_ModelUnbinderController();
    public static T4MVCHostMvcApp.Controllers.SomeAsyncController SomeAsync = new T4MVCHostMvcApp.Controllers.T4MVC_SomeAsyncController();
    public static T4MVCHostMvcApp.Controllers.T4CtrlController T4Ctrl = new T4MVCHostMvcApp.Controllers.T4MVC_T4CtrlController();
    public static T4MVCHostMvcApp.Controllers.TestAttributeYesName1Controller TestAttributeYesName1 = new T4MVCHostMvcApp.Controllers.T4MVC_TestAttributeYesName1Controller();
    public static T4MVCHostMvcApp.Controllers.TestAttributeYesControllerName3 TestAttributeYesControllerName3 = new T4MVCHostMvcApp.Controllers.T4MVC_TestAttributeYesControllerName3();
    public static T4MVCHostMvcApp.Controllers.TestAttributeYesProcessed1Controller TestAttributeYesProcessed1 = new T4MVCHostMvcApp.Controllers.T4MVC_TestAttributeYesProcessed1Controller();
    public static T4MVCHostMvcApp.Controllers.TestAttributeYesProcessed2Controller TestAttributeYesProcessed2 = new T4MVCHostMvcApp.Controllers.T4MVC_TestAttributeYesProcessed2Controller();
    public static T4MVCHostMvcApp.Controllers.TestAttributeYesAbstract2Controller TestAttributeYesAbstract2 = new T4MVCHostMvcApp.Controllers.T4MVC_TestAttributeYesAbstract2Controller();
    public static T4MVCHostMvcApp.Controllers.TestAttributeYesDerivedController TestAttributeYesDerived = new T4MVCHostMvcApp.Controllers.T4MVC_TestAttributeYesDerivedController();
    public static T4MVC.NoControllerMatchingFolder_FooController NoControllerMatchingFolder_Foo = new T4MVC.NoControllerMatchingFolder_FooController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
    public static T4MVCHostMvcApp.Features.Contact.ContactController Contact = new T4MVCHostMvcApp.Features.Contact.T4MVC_ContactController();
    public static T4MVCHostMvcApp.Features.Pictures.PicturesController Pictures = new T4MVCHostMvcApp.Features.Pictures.T4MVC_PicturesController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class breakClass
    {
        public readonly string Name = "break";
        public T4MVCHostMvcApp.Areas.Break.Controllers.PostController Post = new T4MVCHostMvcApp.Areas.Break.Controllers.T4MVC_PostController();
        public T4MVC.@break.SharedController Shared = new T4MVC.@break.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class FeatureFolderAreaClass
    {
        public readonly string Name = "FeatureFolderArea";
        public T4MVCHostMvcApp.Areas.FeatureFolderArea.FeatureFoo.FeatureFooController FeatureFoo = new T4MVCHostMvcApp.Areas.FeatureFolderArea.FeatureFoo.T4MVC_FeatureFooController();
        public T4MVC.FeatureFolderArea.SharedViewsController SharedViews = new T4MVC.FeatureFolderArea.SharedViewsController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class HomeClass
    {
        public readonly string Name = "Home";
        public T4MVCHostMvcApp.Areas.Home.Controllers.HomeController Home = new T4MVCHostMvcApp.Areas.Home.Controllers.T4MVC_HomeController();
        public T4MVC.Home.SharedController Shared = new T4MVC.Home.SharedController();
    }
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ViewResult : System.Web.Mvc.ViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_FileContentResult : System.Web.Mvc.FileContentResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_FileContentResult(string area, string controller, string action, string protocol = null): base(new byte[0], " ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_FileStreamResult : System.Web.Mvc.FileStreamResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_FileStreamResult(string area, string controller, string action, string protocol = null): base(default(System.IO.Stream), " ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_FileResult : System.Web.Mvc.FileResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_FileResult(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    protected override void WriteFile(System.Web.HttpResponseBase response) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_T4MVCHostMvcApp_Misc_MyCustomResult : T4MVCHostMvcApp.Misc.MyCustomResult, IT4MVCActionResult
{
    public T4MVC_T4MVCHostMvcApp_Misc_MyCustomResult(string area, string controller, string action, string protocol = null): base(" ", default(int), default(T4MVCHostMvcApp.Misc.Animal))
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_T4MVCHostMvcApp_Controllers_SomeGenericResult_System_String : T4MVCHostMvcApp.Controllers.SomeGenericResult<System.String>, IT4MVCActionResult
{
    public T4MVC_T4MVCHostMvcApp_Controllers_SomeGenericResult_System_String(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_T4MVCHostMvcApp_Controllers_SomeGenericResult_System_Int32 : T4MVCHostMvcApp.Controllers.SomeGenericResult<System.Int32>, IT4MVCActionResult
{
    public T4MVC_T4MVCHostMvcApp_Controllers_SomeGenericResult_System_Int32(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_T4MVCHostMvcApp_Controllers_SomeGenericResult_System_Collections_Generic_List_System_Tuple_System_String_System_String_System_Int32 : T4MVCHostMvcApp.Controllers.SomeGenericResult<System.Collections.Generic.List<System.Tuple<System.String, System.String, System.Int32>>>, IT4MVCActionResult
{
    public T4MVC_T4MVCHostMvcApp_Controllers_SomeGenericResult_System_Collections_Generic_List_System_Tuple_System_String_System_String_System_Int32(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_PartialViewResult : System.Web.Mvc.PartialViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_PartialViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ViewResultBase : System.Web.Mvc.ViewResultBase, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ViewResultBase(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    protected override System.Web.Mvc.ViewEngineResult FindView(System.Web.Mvc.ControllerContext context) { return default(System.Web.Mvc.ViewEngineResult);  }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string jquery_1_3_2_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.3.2-vsdoc.min.js") ? Url("jquery-1.3.2-vsdoc.min.js") : Url("jquery-1.3.2-vsdoc.js");
        public static readonly string jquery_1_3_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.3.2.min.js") ? Url("jquery-1.3.2.min.js") : Url("jquery-1.3.2.js");
        public static readonly string jquery_1_3_2_min_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.3.2.min-vsdoc.min.js") ? Url("jquery-1.3.2.min-vsdoc.min.js") : Url("jquery-1.3.2.min-vsdoc.js");
        public static readonly string jquery_1_3_2_min_js = Url("jquery-1.3.2.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min-vsdoc.min.js") ? Url("jquery.validate.min-vsdoc.min.js") : Url("jquery.validate.min-vsdoc.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string MicrosoftAjax_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/MicrosoftAjax.debug.min.js") ? Url("MicrosoftAjax.debug.min.js") : Url("MicrosoftAjax.debug.js");
        public static readonly string MicrosoftAjax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/MicrosoftAjax.min.js") ? Url("MicrosoftAjax.min.js") : Url("MicrosoftAjax.js");
        public static readonly string MicrosoftMvcAjax_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/MicrosoftMvcAjax.debug.min.js") ? Url("MicrosoftMvcAjax.debug.min.js") : Url("MicrosoftMvcAjax.debug.js");
        public static readonly string MicrosoftMvcAjax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/MicrosoftMvcAjax.min.js") ? Url("MicrosoftMvcAjax.min.js") : Url("MicrosoftMvcAjax.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string _7_My_Text_File_Space_txt = Url("7 My.Text-File Space.txt");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class @default {
            public const string UrlPath = "~/Content/default";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string Zzz_txt = Url("Zzz.txt");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Empty_Folder {
            public const string UrlPath = "~/Content/Empty Folder";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        }
    
        public static readonly string FileWithNoExtension = Url("FileWithNoExtension");
        public static readonly string Hello_World_txt = Url("Hello World.txt");
        public static readonly string Hello_World_txt_ = Url("Hello$World.txt");
        public static readonly string Hello_World_txt__ = Url("Hello+World.txt");
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class SomeRandomName {
            public const string UrlPath = "~/Content/SomeRandomName";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class SomeRandomName_ {
                public const string UrlPath = "~/Content/SomeRandomName/SomeRandomName";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string Hello_World_txt = Url("Hello World.txt");
                public static readonly string Hello_World_txt_ = Url("Hello$World.txt");
                public static readonly string Hello_World_txt__ = Url("Hello+World.txt");
                public static readonly string SomeRandomName_txt = Url("SomeRandomName.txt");
            }
        
        }
    
        public static readonly string StyleSheet_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/StyleSheet.min.css") ? Url("StyleSheet.min.css") : Url("StyleSheet.css");
        public static readonly string StyleSheet_min_css = Url("StyleSheet.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Sub_Content_folder_test {
            public const string UrlPath = "~/Content/Sub Content-folder.test";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string SomeT4_tt = Url("SomeT4.tt");
            public static readonly string SomeT41_txt = Url("SomeT41.txt");
            public static readonly string SomeT4_txt = Url("SomeT4.txt");
        }
    
    }


    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class ContentStatic {
        public const string UrlPath = "~/ContentStatic";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class TextFiles {
            public const string UrlPath = "~/ContentStatic/TextFiles";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string readme_txt = Url("readme.txt");
        }
    
    }

    public static partial class ContentStatic {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Scripts {
            public const string UrlPath = "~/ContentStatic/Scripts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string SomeOtherScript_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/SomeOtherScript.min.js") ? Url("SomeOtherScript.min.js") : Url("SomeOtherScript.js");
        }
    
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Views {
        public const string UrlPath = "~/Views";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Home {
            public const string UrlPath = "~/Views/Home";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string _7_Some_Home_View_Hello_txt = Url("7 Some Home.View-Hello.txt");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class App_LocalResources {
                public const string UrlPath = "~/Views/Home/App_LocalResources";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string Qqq_txt = Url("Qqq.txt");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @default {
                public const string UrlPath = "~/Views/Home/default";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class DisplayTemplates {
                public const string UrlPath = "~/Views/Home/DisplayTemplates";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class EditorTemplates {
                public const string UrlPath = "~/Views/Home/EditorTemplates";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            }
        
            public static readonly string Qqq_txt = Url("Qqq.txt");
            public static readonly string QqQ_txt2 = Url("QqQ.txt2");
            public static readonly string Qqq_txt3 = Url("Qqq.txt3");
            public static readonly string SomeLinkedFile_txt = Url("SomeLinkedFile.txt");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class SomeName {
                public const string UrlPath = "~/Views/Home/SomeName";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class SomeName_ {
                    public const string UrlPath = "~/Views/Home/SomeName/SomeName";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string SomeName_txt = Url("SomeName.txt");
                }
            
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Sub_Home {
                public const string UrlPath = "~/Views/Home/Sub Home";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Nested_Sub {
                    public const string UrlPath = "~/Views/Home/Sub Home/Nested-Sub";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string _99_Super_Nested_View_txt = Url("99 Super~Nested-View.txt");
                }
            
                public static readonly string Qqq_txt = Url("Qqq.txt");
                public static readonly string string_txt = Url("string.txt");
                public static readonly string T4View_tt = Url("T4View.tt");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class NoControllerMatchingFolder_Foo {
            public const string UrlPath = "~/Views/NoControllerMatchingFolder.Foo";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string Abcd_txt = Url("Abcd.txt");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Shared {
            public const string UrlPath = "~/Views/Shared";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string Hello_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Hello.min.js") ? Url("Hello.min.js") : Url("Hello.js");
            public static readonly string Site_Master = Url("Site.Master");
        }
    
        public static readonly string Web_config = Url("Web.config");
    }


    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Features {
        public const string UrlPath = "~/Features";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Contact {
            public const string UrlPath = "~/Features/Contact";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string Index_txt = Url("Index.txt");
        }
    
    }

    public static partial class Features {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Pictures {
            public const string UrlPath = "~/Features/Pictures";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string Detail_txt = Url("Detail.txt");
            public static readonly string Index_txt = Url("Index.txt");
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Areas {
        public const string UrlPath = "~/Areas";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class @break {
            public const string UrlPath = "~/Areas/break";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Views {
                public const string UrlPath = "~/Areas/break/Views";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Shared {
                    public const string UrlPath = "~/Areas/break/Views/Shared";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string SharedAreaView_txt = Url("SharedAreaView.txt");
                }
            
                public static readonly string Web_config = Url("Web.config");
            }
        
        }
    }

    public static partial class Areas {
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class FeatureFolderArea {
            public const string UrlPath = "~/Areas/FeatureFolderArea";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class FeatureFoo {
                public const string UrlPath = "~/Areas/FeatureFolderArea/FeatureFoo";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string Foobar_txt = Url("Foobar.txt");
                public static readonly string Index_txt = Url("Index.txt");
            }
        
        }
    }

    public static partial class Areas {
    
        public static partial class FeatureFolderArea {
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class SharedViews {
                public const string UrlPath = "~/Areas/FeatureFolderArea/SharedViews";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string SharedView_txt = Url("SharedView.txt");
            }
        
        }
    }

    public static partial class Areas {
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Home {
            public const string UrlPath = "~/Areas/Home";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Views {
                public const string UrlPath = "~/Areas/Home/Views";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Home {
                    public const string UrlPath = "~/Areas/Home/Views/Home";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class EditorTemplates {
                        public const string UrlPath = "~/Areas/Home/Views/Home/EditorTemplates";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    }
                
                    public static readonly string SomeHomeView_txt = Url("SomeHomeView.txt");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Shared {
                    public const string UrlPath = "~/Areas/Home/Views/Shared";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                }
            
                public static readonly string Web_config = Url("Web.config");
            }
        
        }
    }

    public static partial class Areas {
    
        public static partial class Home {
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Content {
                public const string UrlPath = "~/Areas/Home/Content";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                public static readonly string Home_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Home.min.css") ? Url("Home.min.css") : Url("Home.css");
            }
        
        }
    }
    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public static readonly string jquery_1_3_2_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.3.2.js"); 
                public static readonly string jquery_1_3_2_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.3.2.min.js"); 
                public static readonly string jquery_validate_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.js"); 
                public static readonly string jquery_validate_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.min.js"); 
                public static readonly string MicrosoftAjax_debug_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/MicrosoftAjax.debug.js"); 
                public static readonly string MicrosoftAjax_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/MicrosoftAjax.js"); 
                public static readonly string MicrosoftMvcAjax_debug_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/MicrosoftMvcAjax.debug.js"); 
                public static readonly string MicrosoftMvcAjax_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/MicrosoftMvcAjax.js"); 
            }
        }
        public static partial class Content 
        {
            public static partial class @default 
            {
                public static class Assets
                {
                }
            }
            public static partial class Empty_Folder 
            {
                public static class Assets
                {
                }
            }
            public static partial class SomeRandomName 
            {
                public static partial class SomeRandomName_ 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class Sub_Content_folder_test 
            {
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public static readonly string Site_css = T4MVCHelpers.ProcessAssetPath("~/Content/Site.css");
                public static readonly string StyleSheet_css = T4MVCHelpers.ProcessAssetPath("~/Content/StyleSheet.css");
                public static readonly string StyleSheet_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/StyleSheet.min.css");
            }
        }
        public static partial class ContentStatic 
        {
            public static partial class TextFiles 
            {
                public static class Assets
                {
                }
            }
        }
        public static partial class ContentStatic 
        {
            public static partial class Scripts 
            {
                public static class Assets
                {
                    public static readonly string SomeOtherScript_js = T4MVCHelpers.ProcessAssetPath("~/ContentStatic/Scripts/SomeOtherScript.js"); 
                }
            }
        }
        public static partial class Views 
        {
            public static partial class Home 
            {
                public static partial class App_LocalResources 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class @default 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class DisplayTemplates 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class EditorTemplates 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class SomeName 
                {
                    public static partial class SomeName_ 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static partial class Sub_Home 
                {
                    public static partial class Nested_Sub 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class NoControllerMatchingFolder_Foo 
            {
                public static class Assets
                {
                }
            }
            public static partial class Shared 
            {
                public static class Assets
                {
                    public static readonly string Hello_js = T4MVCHelpers.ProcessAssetPath("~/Views/Shared/Hello.js"); 
                }
            }
            public static class Assets
            {
            }
        }
        public static partial class Features 
        {
            public static partial class Contact 
            {
                public static class Assets
                {
                }
            }
        }
        public static partial class Features 
        {
            public static partial class Pictures 
            {
                public static class Assets
                {
                }
            }
        }
        public static partial class Areas 
        {
            public static partial class @break 
            {
                public static partial class Views 
                {
                    public static partial class Shared 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
            }
        }
        public static partial class Areas 
        {
            public static partial class FeatureFolderArea 
            {
                public static partial class FeatureFoo 
                {
                    public static class Assets
                    {
                    }
                }
            }
        }
        public static partial class Areas 
        {
            public static partial class FeatureFolderArea 
            {
                public static partial class SharedViews 
                {
                    public static class Assets
                    {
                    }
                }
            }
        }
        public static partial class Areas 
        {
            public static partial class Home 
            {
                public static partial class Views 
                {
                    public static partial class Home 
                    {
                        public static partial class EditorTemplates 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                        }
                    }
                    public static partial class Shared 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
            }
        }
        public static partial class Areas 
        {
            public static partial class Home 
            {
                public static partial class Content 
                {
                    public static class Assets
                    {
                        public static readonly string Home_css = T4MVCHelpers.ProcessAssetPath("~/Areas/Home/Content/Home.css");
                    }
                }
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


